routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/home', 'Fotos@mostrar');


Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/galeria', 'HomeController@fotos');
Route::get('/habitacion', 'HomeController@habitacion');
Route::get('/ubicacion', 'HomeController@ubicacion');


//Fotos

Route::resource('/fotos', 'Fotos');

app/Foto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Foto extends Model
{
    //
    protected $fillable = [
        'titulo', 'descripcion', 'urlImg',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Fotos.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Foto;
use Storage;
// Utilidad para las fechas.
use Carbon\Carbon;

class Fotos extends Controller
{

        public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        //
    }

     public function mostrar()

    {
        $fotos = Foto::all();
        return view('home')->with(['fotos' => $fotos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    public function store(Request $request)
    {
          $this->validate($request, [
            'titulo' => 'required',
            'descripcion' => 'required',
            //'urlImg'=>'required|image|max:20000',
            ]);

          $foto = new Foto();
          $foto->titulo = $request->titulo;
          $foto->descripcion = $request->descripcion;  

          //para guardar fotos

          $img = $request->file('urlImg');
          $ruta='/imgFotos/';
          //$file_route = time().'_'.$img->guessExtension();
          $file_route = time().'_'.$img->guessExtension();
          //Storage::disk('imgFotos')->put($file_route, file_get_contents( $img->getRealPath() ));
          $img->move(getcwd().$ruta,$file_route);

          $foto->urlImg = $file_route;
          
          if($foto->save()){

            return back()->with('msj', 'La foto ha sido guardada');

          } else {
            return back()->with('errormsj', 'Error al guardar la imagen');
          }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $foto = Foto::find($id);
        return view('home')->with(['edit' => true, 'foto' => $foto]);

    }


    public function update(Request $request, $id)
    {
            $this->validate($request, [
            'titulo' => 'required',
            'descripcion' => 'required',
            //'urlImg'=>'required|image|max:20000',
            ]);

          $foto = Foto::find($id);
          $foto->titulo = $request->titulo;
          $foto->descripcion = $request->descripcion;  

          //para guardar fotos

          $img = $request->file('urlImg');
          $file_route = time().'_'.$img->getClientOriginalName();
          Storage::disk('imgFotos')->put($file_route, file_get_contents( $img->getRealPath() ));
          Storage::disk('imgFotos')->delete($request->img);

          $foto->urlImg = $file_route;
          
          if($foto->save()){

            return redirect('home')->with('msj', 'La foto ha sido guardada');
            
          } else {
            return back()->with('errormsj', 'Error al guardar la imagen');
          }
    }


    public function destroy($id)
    {
        Foto::destroy($id);
        return back();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Foto;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $fotos = Foto::all();
        return view('welcome');
    }

        public function fotos()
    {
        $fotos = Foto::all();
        return view('usuario/galeria')->with(['fotos' => $fotos]);
    }

    public function habitacion()
    {
        return view('usuario/habitacion');
    }

        public function ubicacion()
    {
        return view('usuario/ubicacion');
    }
}

resources/views/admin/admin.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
		<title>Hotel Marianao</title>

		<link href="{{ asset('/css/app.css') }}" rel="stylesheet">
			<!-- CSS Materialize-->
		<link rel="stylesheet" href="{{ asset('plugins/materialize/css/materialize.css') }}">
	    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Bitter|Cedarville+Cursive|Zeyada" rel="stylesheet">
	  <!-- Mis Estilos-->
	  <link rel="stylesheet" href="{{ asset('plugins/materialize/css/estilos.css') }}">

		<!-- Fonts -->
		<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	</head>
	<body>

		<div class="navbar-fixed">
		  <nav class="white" role="navigation">
		      <div class="nav-wrapper">

		        <ul class="left hide-on-med-and-down">
		          <li><a href="{{ url('/register') }}">Registrar</a></li>
		          <li><a href="{{ url('/home') }}">Editar Galeria</a></li>
		        </ul>

		        <ul class="hide-on-med-and-down center">
		          <li class="admin"><h3 class="marianao">Administración</h3></li>
		        </ul>

		        <ul class="right hide-on-med-and-down">
		           <li>
                      <a href="{{ url('/logout') }}" class="btn red" 
                          onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">
                                            Salir
                       </a>

                       <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                          {{ csrf_field() }}
                       </form>
                    </li>
		        </ul>
		     
		        <ul id="nav-mobile" class="side-nav">
		          <li><a href="{{ url('/register') }}">Registrar</a></li>
		          		           <li>
                      <a href="{{ url('/logout') }}"  
                          onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">
                                            Salir
                       </a>

                       <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                          {{ csrf_field() }}
                       </form>

                       <a href="{{ url('/home') }}">Editar Galeria</a>
                    </li>
		        </ul>
		        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
		        </div>
		  </nav>
		</div>

		@yield('content')

		 <!-- Jquery-->
		  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
		  <!-- Compiled and minified JavaScript -->
		  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
		  <!-- Inicializando Carrusel-->
		  <script type="text/javascript">
		  $(document).ready(function(){
		      $('.slider').slider({full_width: true});
		      $('.button-collapse').sideNav();
		  });

		  $(document).ready(function(){
		      $('.parallax').parallax();
		    });
		  </script>
	</body>
</html>

resources/views/admin/template/main.blade.php
<!DOCTYPE html>
<html lang="es">
  
 @include('admin.template.partials.cabecera')

<body>
	@include('admin.template.partials.nav')

	<section>
		@yield('content')
	</section>
  <br><br><br><br><br>
  
  	<!-- Footer -->
  @include('admin.template.partials.footer')
 

  @include('admin.template.partials.scripts')  

 </body>
</html>

resources/views/admin/template/partials/cabecera.blade.php
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
	 <!--  Android 5 Chrome Color-->
	<meta name="theme-color" content="#000">
	<title> @yield('title', 'Default') </title>
  	<!-- CSS Materialize-->
	<link rel="stylesheet" href="{{ asset('plugins/materialize/css/materialize.css') }}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Bitter|Cedarville+Cursive|Zeyada" rel="stylesheet">
  <!-- Mis Estilos-->
  <link rel="stylesheet" href="{{ asset('plugins/materialize/css/estilos.css') }}">
</head>

resources/views/admin/template/partials/footer.blade.php
<footer class="page-footer black">
  <div class="container">
    <div class=" redes">
      <div class="container">
        <center>
          <div class="siguenos">¡Llámanos!</div>
              <h3 class="siguenos">Tel 01 235 328 0064</h3>
        </center>
      </div>
    </div>
  </div>
  <br>
  <div class="contacto container">
    <center>“En la contemplación de la naturaleza y en el silencio, busquemos la armónica belleza de la vida”. 
    <br>(Cora Cané (Periodista Argentina 1923-2016))</center>
  </div>
  <div class="footer-copyright container">
    <center>© Hotel Marianao</center>
  </div>
</footer>

resources/views/admin/template/partials/nav.blade.php
<div class="navbar-fixed">
  <nav class="white" role="navigation">
      <div class="nav-wrapper">

        <ul class="left hide-on-med-and-down">
          <li><a href="{{ url('/') }}">Inicio</a></li>
          <li><a href="">Habitaciones</a></li>
          <li><a href="">Galeria</a></li>
          <li><a href="">Ubicación</a></li>
          <li><a href="{{url('/login')}}">LogIn</a></li>
        </ul>

        <ul class="hide-on-med-and-down center">
          <li class="centro"><h3 class="marianao">Hotel Marianao</h3></li>
        </ul>

        <ul class="right hide-on-med-and-down">
          <li class="fondo"><a href="" class="fondo"><i class="material-icons iconos left">call</i>01 235 328 0064</a></li>
        </ul>
     
        <ul id="nav-mobile" class="side-nav">
          <li><a href="index.html">INICIO</a></li>
          <li><a href="habitaciones.html">HABITACIONES</a></li>
          <li><a href="habitaciones.html">GALERIA</a></li>
          <li><a href="habitaciones.html">UBICACIÓN Y CONTACTO</a></li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
  </nav>
</div>

resources/views/admin/template/partials/scripts.blade.php
 <!-- Jquery-->
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <!-- Inicializando Carrusel-->
  <script type="text/javascript">
  $(document).ready(function(){
      $('.slider').slider({full_width: true});
      $('.button-collapse').sideNav();
  });

  $(document).ready(function(){
      $('.parallax').parallax();
    });
  </script>

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
	<title>Hotel Marianao</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">
		<!-- CSS Materialize-->
	<link rel="stylesheet" href="{{ asset('plugins/materialize/css/materialize.css') }}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Bitter|Cedarville+Cursive|Zeyada" rel="stylesheet">
  <!-- Mis Estilos-->
  	<link rel="stylesheet" href="{{ asset('plugins/materialize/css/estilos.css') }}">
  	<link rel="stylesheet" href="{{ asset('plugins/materialize/css/lightslider.css') }}">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>


</head>
<body class="color fondo-principal">

	<div class="navbar-fixed">
	  <nav class="fondoNav" role="navigation">
	      <div class="nav-wrapper">

	        <ul class="left hide-on-med-and-down">
	          <li><a href="{{ url('/') }}">Inicio</a></li>
	          <li><a href="{{ url('habitacion') }}">Habitaciones</a></li>
	          <li><a href="{{ url('galeria')}}">Galeria</a></li>
	          <li><a href="{{ url('ubicacion')}}">Ubicación</a></li>
	          <li><a href="{{url('/login')}}">LogIn</a></li>
	        </ul>

	        <ul class="">
	          <li class="centro"><h3 class="marianao">Hotel Marianao</h3></li>
	        </ul>

	        <ul class="right hide-on-med-and-down">
	          <li class="fondo"><a href="#" class="fondo"><i class="material-icons iconos left">call</i>01 235 328 0064</a></li>
	        </ul>
	     
	        <ul id="nav-mobile" class="side-nav user">
	          <li><a href="{{ url('/') }}">INICIO</a></li>
	          <li><a href="{{ url('habitacion') }}">HABITACIONES</a></li>
	          <li><a href="{{ url('galeria')}}">GALERIA</a></li>
	          <li><a href="{{ url('ubicacion')}}">UBICACIÓN</a></li>
	        </ul>
	        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
	        </div>
	  </nav>
	</div>

	@yield('content')

	 <!-- Jquery-->
	  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBe11T1nA6jV8ikpKwc45xwU8jtnmcFa4M&callback&signed_in=true&libraries=places&callback=initMap" async defer></script>
       <script src="{{ asset('plugins/materialize/js/ubicacion.js') }}"></script>
	  <!-- Compiled and minified JavaScript -->
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
	  <!-- Inicializando Carrusel-->
	  <script type="text/javascript">
	  $(document).ready(function(){
	      $('.slider').slider({full_width: true});
	      $('.button-collapse').sideNav();
	  });

	  $(document).ready(function(){
	      $('.parallax').parallax();
	    });
	  </script>

	<!--Galeria-->
	<script src="{{ asset('plugins/materialize/js/lightslider.js') }}"></script> 
    <script>
    	 $(document).ready(function() {
			$("#content-slider").lightSlider({
                loop:true,
                keyPress:true
            });
            $('#image-gallery').lightSlider({
                gallery:true,
                item:1,
                thumbItem:9,
                slideMargin: 0,
                speed:500,
                auto:true,
                loop:true,
                onSliderLoad: function() {
                    $('#image-gallery').removeClass('cS-hidden');
                }  
            });
		});
    </script>
</body>
</html>

resources/views/fotos/actualizar-foto.blade.php
@extends('app')

@section('content')
<div class="container-fluid">
	<form class="form-horizontal" role="form" method="POST" action="{{url('/validado/fotos/actualizar-foto')}}" enctype="multipart/form-data">
		<input type="hidden" name="_token" value="{{ csrf_token() }}" required>
		<input type="hidden" name="id" value="{{ $foto->id }}" required>

		<div class="form-group required">
			<label class="col-md-4 control-label">Nombre</label>
			<div class="col-md-6">
				<input type="text" class="form-control" name="nombre" value="{{ $foto->nombre }}" required>
			</div>
		</div>


		<div class="form-group required">
			<label class="col-md-4 control-label">Descripción</label>
			<div class="col-md-6">
				<textarea class="form-control" name="descripcion" rows="3" required>{{$foto->descripcion}}</textarea>
			</div>
		</div>

		<div class="form-group required">
			<label class="col-md-4 control-label">Imagen max: 20MB</label>
			<div class="col-md-6">
				<input type="file" class="form-control" name="imagen">
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-6 col-md-offset-4">
				<button type="submit" class="btn btn-primary">
					Actualizar Imagen
				</button>
			</div>
		</div>
	</form>
</div>
@endsection

resources/views/fotos/crear-foto.blade.php
@extends('app')

@section('content')
<div class="container-fluid">
	<form class="form-horizontal" role="form" method="POST" action="{{url('/fotos/crear-foto')}}?id={{$id}}" enctype="multipart/form-data">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">

		<div class="form-group required">
			<label class="col-md-4 control-label">Nombre</label>
			<div class="col-md-6">
				<input type="text" class="form-control" name="nombre" value="{{ old('nombre') }}" required>
			</div>
		</div>


		<div class="form-group required">
			<label class="col-md-4 control-label">Descripción</label>
			<div class="col-md-6">
				<textarea class="form-control" name="descripcion" rows="3" required>{{old('descripcion')}}</textarea>
			</div>
		</div>

		<div class="form-group required">
			<label class="col-md-4 control-label">Imagen max: 20MB</label>
			<div class="col-md-6">
				<input type="file" class="form-control" name="imagen" required>
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-6 col-md-offset-4">
				<button type="submit" class="btn btn-primary">
					Subir Imagen
				</button>
			</div>
		</div>
	</form>
</div>
@endsection

resources/views/fotos/mostrar.blade.php
@extends('app')

@section('content')

@if (Session::has('creada'))
<div class="alert alert-success">
	{{Session::get('creada')}}
</div>
@endif 

@if (Session::has('editada'))
<div class="alert alert-success">
	{{Session::get('editada')}}
</div>
@endif 

@if (Session::has('eliminada'))
<div class="alert alert-success">
	{{Session::get('editada')}}
</div>
@endif 

<div class="container-fluid">
<p><a href="{{url('/fotos/crear-foto')}}" class="btn btn-primary" role="button">Crear Foto</a></p>
@if(sizeof($fotos) > 0)
	@foreach($fotos as $index => $foto)
		@if($index%4 == 0)
		<div class="row">
		@endif
		  <div class="col-sm-6 col-md-3">
		    <div class="thumbnail">
		    	<img src={{asset($foto->ruta)}}>
		      <div class="caption">
		        <h3>{{$foto->nombre}}</h3>
		        <p>{{$foto->descripcion}}</p>
		      </div>
		      <p><a href="{{url('/validado/fotos/actualizar-foto')}}/{{$foto->id}}" class="btn btn-primary" role="button">Editar Foto</a></p>
		      <form action="{{url('/validado/fotos/eliminar-foto')}}" method="POST">
				<input type="hidden" name="_token" value="{{ csrf_token() }}" required>
				<input type="hidden" name="id" value="{{$foto->id}}" required>
				<input class="btn btn-danger" role="button" type="submit" value="Eliminar Foto"/>
			</form>
		    </div>
		  </div>
		@if(($index+1)%4 == 0)
		</div>
		@endif
	@endforeach
@else
<div class="alert alert-danger">
	<p>Al parecer este album no tiene fotos. Crea una.</p>
</div>
@endif
</div>
@endsection

resources/views/home.blade.php
@extends('admin.admin')

@section('content')
<div class="container">
    <br><br>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-body">
                @if(isset($edit))
                     @include('layouts.modificar');   
                @else
                    @include('layouts.formulario');
                    @include('layouts.tabla');
                @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/image-upload.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Laravel 5.3 Image Upload with Validation example</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>

<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading"><h2>Laravel 5.3 Image Upload with Validation example</h2></div>
  <div class="panel-body">

	  	@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Whoops!</strong> There were some problems with your input.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
						<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif

		@if ($message = Session::get('success'))
		<div class="alert alert-success alert-block">
			<button type="button" class="close" data-dismiss="alert">×</button>
		        <strong>{{ $message }}</strong>
		</div>
		<img src="/images/{{ Session::get('path') }}">
		@endif

		<form action="{{ url('image-upload') }}" enctype="multipart/form-data" method="POST">
			{{ csrf_field() }}
			<div class="row">
				<div class="col-md-12">
					<input type="file" name="image" />
				</div>
				<div class="col-md-12">
					<button type="submit" class="btn btn-success">Upload</button>
				</div>
			</div>
		</form>

  </div>
</div>

</div>

</body>
</html>

resources/views/layouts/formulario.blade.php
@if(session()->has('msj'))
<div class="alert alert-success" role="alert">
  {{session('msj')}}
</div>
@endif
@if(session()->has('errormsj'))
<div class="alert alert-danger">
  {{session('errormsj')}}
</div>
@endif
<form method="POST" role="form" action="{{url('fotos')}}" enctype="multipart/form-data">
   {{ csrf_field() }}
  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <input type="text" name="titulo" class="validate">
          <label for="titulo">Título</label>
          @if($errors->has('titulo'))
           <span style="color:red;">{{$errors->first('titulo')}}</span>
          @endif
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <textarea name="descripcion" class="materialize-textarea"></textarea>
          <label for="descripcion">Descripción</label>

           @if($errors->has('descripcion'))
             <span style="color:red;">{{$errors->first('descripcion')}}
             </span>
          @endif

        </div>
      </div>

      <form action="#">
        <div class="file-field input-field">
          <div class="btn">
            <span>Imagen</span>
            <input name="urlImg" type="file">
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text" name="urlImg">
          </div>
        </div>
      </form>
    </form>
      <div class="col s6"> 
      <br>
       <button class="btn waves-effect waves-light  " type="submit" name="action">Crear
       </button>
      </div>
  </div>
</form> 

resources/views/layouts/modificar.blade.php
 @if(session()->has('msj'))
<div class="alert alert-success" role="alert">
  {{session('msj')}}
</div>
@endif
@if(session()->has('errormsj'))
<div class="alert alert-danger">
  {{session('errormsj')}}
</div>
@endif

@if(isset($foto))
<form method="POST" role="form" action="{{ route('fotos.update', $foto->id) }}" enctype="multipart/form-data">
<input name="_method" type="hidden" value="PUT">
<input class="hide" type="text" name="img" value="{{$foto->urlImg}}">


   {{ csrf_field() }}
  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <input type="text" name="titulo" class="validate" value="{{$foto->titulo}}">
          <label for="titulo">Título</label>
          @if($errors->has('titulo'))
           <span style="color:red;">{{$errors->first('titulo')}}</span>
          @endif
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
        <label for="descripcion">Descripción</label>
          <textarea name="descripcion" class="materialize-textarea"> {{$foto->descripcion}}</textarea>
          

           @if($errors->has('descripcion'))
             <span style="color:red;">{{$errors->first('descripcion')}}
             </span>
          @endif

        </div>
      </div>

      <form action="#">
        <div class="file-field input-field">
          <div class="btn">
            <span>Imagen</span>
            <input name="urlImg" type="file" >
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text" name="urlImg">
          </div>
        </div>
      </form>
    </form>
      <div class="col s6"> 
      <br>
       <button class="btn waves-effect waves-light red" type="submit" name="action">Modificar
       </button>
      </div>
  </div>
</form> 
@endif

resources/views/layouts/tabla.blade.php
<table class="responsive-table highlight">
	@if(isset($fotos))
	<thead>
		<th>Titulo</th>
		<th>Descripción</th>
		<th>Imagen</th>
		<th></th>
	</thead>

	<tbody>
		@foreach($fotos as $n)
			<tr>
				<td>{{ $n->titulo }}</td>
				<td>{{ $n->descripcion }}</td>
				<td>
					<img class="responsive-img" width="100" src="imgFotos/{{$n->urlImg}}">
				</td>
				<td>
					<a href="fotos/{{$n->id}}/edit" class="btn btn-xs blue">Modificar</a>

					<form action="{{route('fotos.destroy',$n->id)}}" method="POST" >
						<input name="_method" type="hidden" value="DELETE">
						   {{ csrf_field() }}
						<input type="submit" class="btn btn-xs red" value="Eliminar">
					</form>
				</td>				
			</tr>
		@endforeach
	</tbody>
	@endif
</table>

resources/views/partials/footer.blade.php
<head>
  
</head>
<footer class="page-footer fondoFooter">
  <div class="container">
      
      <div class="llamanos posicion1">¡Llámanos!
        <div class="material-icons iconos left">01 235 328 0064</div>
      </div>
        
        
      <div class="llamanos posicion2">¡Síguenos!
        <div>  
          <a href="https://www.facebook.com/Hotel-Marianao-203910125452/"><img class="posicion" src="imgs/redes/f2.png"></a>   
        </div>
      </div>
        
 
  </div>
  <br>
  <div class="contacto container">
    <center>“En la contemplación de la naturaleza y en el silencio, busquemos la armónica belleza de la vida”
    <br>Cora Cané (Periodista Argentina 1923-2016)</center>
  </div>
  <div class="footer-copyright container">
    <center>© Hotel Marianao</center>
  </div>
</footer>

resources/views/usuario/galeria.blade.php
@extends('app')

@section('content')
    
  <div class="flex-center position-ref full-height">   <div class="container">
  <br>
        <div class="row">
           @if(isset($fotos))
             @foreach($fotos as $n)
               <div class="col s4 img">
                               
                <img class="materialboxed responsive-img" data-caption="{{$n->descripcion}}}" src="imgFotos/{{$n->urlImg}}">
                <br>
       
               </div>
             @endforeach
           @endif
                        
          </div>
        </div>
       </div>
   </div>
  

  @include('partials.footer')
@endsection

resources/views/usuario/ubicacion.blade.php
@extends('app')




@section('content')

<br><br>
  
  <div class="row">
    <div class="col s4">
      <div id="map" class="tamanoMapa"></div>  
    </div>
    <div class="col s6 precio">
    		<br><br>
          Ubicado muy cerca de la Costa Esmeralda cuenta con amplias y confortables habitaciones con aire acondicionado, ventilador de techo, televisión por cable, internet inalámbrico y agua caliente día y noche.
    </div>
  </div>

@include('partials.footer')
@endsection